services:
  - type: web
    name: fortune-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://creaternuri_db_user:pGdSH0m8VAZssLV6@cluster0.b5di47j.mongodb.net/fortune?retryWrites=true&w=majority&appName=Cluster0
    healthCheckPath: /api/health
